name: Build Container
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build the Docker image (amd 64)
      run: docker build . --file Dockerfile --tag sebd/dvb-mqtt:latest

    - name: Build the Docker image (arm)
      run: docker build . --file Dockerfile --tag sebd/dvb-mqtt-rpi:latest

    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin

    - name: Publish the Docker Images
      run: docker push sebd/dvb-mqtt:latest
      run: docker push sebd/dvb-mqtt-rpi:latest

    - name: Logot of the DockerHub Registry
      run: docker logout

