name: Build Container
on: [push]
jobs:

  build:
    name: Docker Build and Publish
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Build the Docker image (amd 64)
      run: docker build . --file Dockerfile --tag sebd/dvb-mqtt:latest

    - name: Build the Docker image (arm)
      run: docker build . --file Dockerfile --tag sebd/dvb-mqtt-rpi:latest

    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin

    - name: Publish the amd64 Docker Image
      run: docker push sebd/dvb-mqtt:latest
    
    - name: Publish the arm Docker Image
      run: docker push sebd/dvb-mqtt-rpi:latest

    - name: Logot of the DockerHub Registry
      run: docker logout

